'use client';

import { useMemo, useState } from 'react';
import { jsPDF } from 'jspdf';
import { analyticsMetrics as defaultMetrics, type Metric } from '../data/metrics';
import { recentActivity as activityData } from '../data/recentActivity';
import type { User } from 'firebase/auth';

type ReportBuilderProps = {
  currentUser: User | null;
  onReportCreated: () => void;
};

type FilterOptions = {
  range: string;
  category: string;
  metrics: string[];
  sections: string[];
};

const ranges = ['7d', '30d', '90d', '1y'];
const categories = ['All customers', 'Enterprise', 'SMB', 'Trials'];
const sections = ['Summary', 'Charts', 'Tables', 'Insights'];
const availableMetrics = defaultMetrics.map((metric) => metric.title);

const defaultFilters: FilterOptions = {
  range: '30d',
  category: 'All customers',
  metrics: ['Revenue', 'Active users', 'Conversion rate'],
  sections: ['Summary', 'Tables', 'Insights'],
};

function arrayBufferToBase64(buffer: ArrayBuffer) {
  let binary = '';
  const bytes = new Uint8Array(buffer);
  const len = bytes.byteLength;
  for (let i = 0; i < len; i += 1) {
    binary += String.fromCharCode(bytes[i]);
  }
  return window.btoa(binary);
}

export default function ReportBuilder({ currentUser, onReportCreated }: ReportBuilderProps) {
  const [title, setTitle] = useState('InsightBoard custom report');
  const [filters, setFilters] = useState<FilterOptions>(defaultFilters);
  const [status, setStatus] = useState<string>('Ready to generate');
  const [isGenerating, setIsGenerating] = useState(false);

  const selectedMetrics = useMemo(
    () => defaultMetrics.filter((metric) => filters.metrics.includes(metric.title)),
    [filters.metrics]
  );

  const summaryText = useMemo(() => {
    const growthMetrics = selectedMetrics.map((metric) => metric.title).join(', ');
    return `This report covers ${filters.category.toLowerCase()} performance over the last ${filters.range}. Key metrics include ${growthMetrics}.`;
  }, [filters.category, filters.range, selectedMetrics]);

  const handleToggleMetric = (metric: string) => {
    setFilters((current) => ({
      ...current,
      metrics: current.metrics.includes(metric)
        ? current.metrics.filter((item) => item !== metric)
        : [...current.metrics, metric],
    }));
  };

  const handleToggleSection = (section: string) => {
    setFilters((current) => ({
      ...current,
      sections: current.sections.includes(section)
        ? current.sections.filter((item) => item !== section)
        : [...current.sections, section],
    }));
  };

  const generateReport = async () => {
    if (!currentUser) {
      setStatus('Sign in to generate reports.');
      return;
    }

    setIsGenerating(true);
    setStatus('Generating PDF...');

    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    doc.setFontSize(18);
    doc.text(title, 40, 60);
    doc.setFontSize(10);
    doc.text(`Generated by ${currentUser.email ?? currentUser.uid}`, 40, 85);
    doc.text(`Date: ${new Date().toLocaleString()}`, 40, 100);
    doc.text(`Filters: ${filters.range}, ${filters.category}`, 40, 115);

    let currentY = 150;

    if (filters.sections.includes('Summary')) {
      doc.setFontSize(12);
      doc.text('Summary', 40, currentY);
      currentY += 18;
      doc.setFontSize(10);
      const summaryLines = doc.splitTextToSize(summaryText, 500);
      doc.text(summaryLines, 40, currentY);
      currentY += summaryLines.length * 14 + 20;
    }

    if (filters.sections.includes('Charts')) {
      doc.setFontSize(12);
      doc.text('Chart data', 40, currentY);
      currentY += 20;
      doc.setFontSize(10);
      selectedMetrics.slice(0, 3).forEach((metric) => {
        const value =
          metric.title === 'Revenue'
            ? '$124K'
            : metric.title === 'Active users'
            ? '16.2K'
            : metric.title === 'Conversion rate'
            ? '7.8%'
            : 'N/A';
        doc.text(`- ${metric.title}: ${value}`, 50, currentY);
        currentY += 16;
      });
      currentY += 14;
    }

    if (filters.sections.includes('Tables')) {
      doc.setFontSize(12);
      doc.text('Selected table data', 40, currentY);
      currentY += 20;
      doc.setFontSize(10);
      selectedMetrics.forEach((metric) => {
        doc.text(`• ${metric}`, 50, currentY);
        currentY += 16;
      });
      currentY += 14;
    }

    if (filters.sections.includes('Insights')) {
      doc.setFontSize(12);
      doc.text('Key insights', 40, currentY);
      currentY += 20;
      doc.setFontSize(10);
      doc.text(
        `The data shows a steady upward trend in ${selectedMetrics.join(', ')} for the selected period and category. Use this report to drive next-step decisions with stakeholders.`, 
        40,
        currentY,
        { maxWidth: 500 }
      );
      currentY += 40;
    }

    const pdfBlob = await doc.output('blob');
    const arrayBuffer = await pdfBlob.arrayBuffer();
    const pdfBase64 = `data:application/pdf;base64,${arrayBufferToBase64(arrayBuffer)}`;

    setStatus('Uploading report metadata...');

    const response = await fetch('/api/reports', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userId: currentUser.uid,
        title,
        filters: { range: filters.range, category: filters.category, metrics: filters.metrics },
        sections: filters.sections,
        summary: summaryText,
        pdfBase64,
      }),
    });

    if (!response.ok) {
      setStatus('Failed to save report.');
      setIsGenerating(false);
      return;
    }

    setStatus('Report generated successfully.');
    setIsGenerating(false);
    setFilters(defaultFilters);
    onReportCreated();
  };

  return (
    <div className="rounded-[32px] border border-panel bg-panel/95 p-6 shadow-soft">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-sm uppercase tracking-[0.28em] text-muted">Report builder</p>
          <h2 className="mt-2 text-2xl font-semibold">Create a custom PDF report</h2>
          <p className="mt-3 text-sm leading-7 text-muted">
            Choose report sections, filters, and metrics to produce a tailored summary for your team.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={generateReport}
            disabled={isGenerating}
            className="rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand/90 disabled:opacity-60"
          >
            {isGenerating ? 'Generating…' : 'Generate PDF'}
          </button>
        </div>
      </div>

      <div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_0.95fr]">
        <div className="space-y-6 rounded-[28px] bg-surface/90 p-6">
          <label className="block text-sm text-muted">
            Report title
            <input
              type="text"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              className="mt-3 w-full rounded-3xl border border-panel bg-base px-4 py-3 text-sm text-white outline-none transition focus:border-brand"
            />
          </label>

          <div className="grid gap-4 sm:grid-cols-2">
            <label className="block text-sm text-muted">
              Date range
              <select
                value={filters.range}
                onChange={(event) => setFilters((current) => ({ ...current, range: event.target.value }))}
                className="mt-3 w-full rounded-3xl border border-panel bg-base px-4 py-3 text-sm text-white outline-none transition focus:border-brand"
              >
                {ranges.map((range) => (
                  <option key={range} value={range}>
                    {range}
                  </option>
                ))}
              </select>
            </label>
            <label className="block text-sm text-muted">
              Category
              <select
                value={filters.category}
                onChange={(event) => setFilters((current) => ({ ...current, category: event.target.value }))}
                className="mt-3 w-full rounded-3xl border border-panel bg-base px-4 py-3 text-sm text-white outline-none transition focus:border-brand"
              >
                {categories.map((category) => (
                  <option key={category} value={category}>
                    {category}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <div className="space-y-4">
            <p className="text-sm uppercase tracking-[0.28em] text-muted">Select metrics</p>
            <div className="grid gap-3 sm:grid-cols-2">
              {availableMetrics.map((metric) => (
                <button
                  type="button"
                  key={metric}
                  onClick={() => handleToggleMetric(metric)}
                  className={`rounded-2xl border px-4 py-3 text-left text-sm transition ${
                    filters.metrics.includes(metric)
                      ? 'border-brand bg-brand-soft text-brand'
                      : 'border-panel bg-surface text-white hover:bg-surface/90'
                  }`}
                >
                  {metric}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-4">
            <p className="text-sm uppercase tracking-[0.28em] text-muted">Report sections</p>
            <div className="grid gap-3 sm:grid-cols-2">
              {sections.map((section) => (
                <button
                  key={section}
                  type="button"
                  onClick={() => handleToggleSection(section)}
                  className={`rounded-2xl border px-4 py-3 text-left text-sm transition ${
                    filters.sections.includes(section)
                      ? 'border-brand bg-brand-soft text-brand'
                      : 'border-panel bg-surface text-white hover:bg-surface/90'
                  }`}
                >
                  {section}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="rounded-[28px] border border-panel bg-surface/90 p-6 text-sm text-muted shadow-soft">
          <p className="text-sm uppercase tracking-[0.28em] text-muted">Preview</p>
          <div className="mt-4 space-y-4">
            <div>
              <p className="text-white">Title</p>
              <p className="mt-2 text-base text-white">{title}</p>
            </div>
            <div>
              <p className="text-white">Filters</p>
              <p className="mt-2">{filters.range} / {filters.category}</p>
            </div>
            <div>
              <p className="text-white">Metrics</p>
              <p className="mt-2 text-white">{filters.metrics.join(', ')}</p>
            </div>
            <div>
              <p className="text-white">Sections</p>
              <p className="mt-2 text-white">{filters.sections.join(', ')}</p>
            </div>
            <div className="rounded-3xl border border-panel bg-base/80 p-4">
              <p className="text-sm uppercase tracking-[0.24em] text-muted">Summary text</p>
              <p className="mt-2 text-sm leading-6 text-white">{summaryText}</p>
            </div>
            <div className="rounded-3xl border border-panel bg-base/80 p-4">
              <p className="text-sm uppercase tracking-[0.24em] text-muted">Status</p>
              <p className="mt-2 text-sm leading-6 text-white">{status}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
